name: CI
on:
  push:
    branches: [main]
  pull_request: ~

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  DEFAULT_UV: "0.3.0"
  SOURCE: "elkm1_lib"

jobs:
  check-quality:
    # strategy:
    #   fail-fast: false

    runs-on: ubuntu-latest

    steps:
      - name: Check out code from GitHub
        uses: actions/checkout@v4.1.7

      - name: Set up uv
        run: curl -LsSf https://astral.sh/uv/${{ env.DEFAULT_UV }}/install.sh | sh

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Run pylint
        run: uv run pylint $${{ env.SOURCE }}

      - name: Check code formatting
        run: uv run black --check

      - name: Check typing
        run: uv run mypy --show-error-codes --strict elkm1_lib
        # run: |
        #   source .venv/bin/activate
        #   mypy --show-error-codes --strict elkm1_lib

      - name: Run isort check
        run: uv run isort --check-only --profile black .
        # run: |
        #   source .venv/bin/activate
        #   isort --check-only --profile black .

      - name: Run pytest
        run: uv run pytest test
        # run: |
        #   source .venv/bin/activate
        #   poetry install --no-interaction
        #   pytest test
